apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: m6bds03dk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m6bds03dk-python 
  name: m6bds03dk-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: m6bds03dk-python
    weight: 100 
