apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m6bds03dk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m6bds03dk-python 
  name: m6bds03dk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: m6bds03dk-python 
